language: ruby
rvm:
  - 1.9.3
gemfile: Gemfile  
bundler_args: "--without development production" 

env: 
  - DB=postgresql
  - DB=sqlite
  - DB=mysql

matrix:
  allow_failures:
    - env: DB=postgresql
    - env: DB=mysql

before_script:
  - psql -c 'create database edge_test' -U postgres
  - "bundle exec rake db:migrate"
  - "bundle exec rake db:test:prepare"
  # - "sh -c 'RAILS_ENV=test bundle exec rake db:create db:schema:load --trace'"

script: "bundle exec rspec spec"

# branches:
#   only:
#     - master
