sqlite: &sqlite
  adapter: sqlite3
  database: db/<%= Rails.env %>.sqlite3

postgresql: &postgresql
  adapter: postgresql
  database: edge_<%= Rails.env %>
#   username: andy
#   password:
#   min_messages: ERROR

defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  <<: *<%= ENV['DB'] || "postgresql" %>   # whatever is in this line will be the DB

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
